ProyectoWeb1/urls.py
#Urls del Proyecto
from django.contrib import admin
from django.urls import path,include

#Primero Importe las Vista para hacer una prueba from ProyectoWebApp import views
# Eso sirve para enclacer diferentes aplicaciones
urlpatterns = [
    path('admin/', admin.site.urls),

    # Servicios

    path('servicios/', include('servicios.urls')),

    #Irnos a nuestra Aplicacion

    path('blog/',include('blog.urls')),

    path('contacto/',include('contacto.urls')),


    path('',include('ProyectoWebApp.urls')),

    path('tienda/',include('tienda.urls')),

    path('carro/',include('carro.urls')),
   
    

]      




#Este urls es para todas las aplicaciones que forma parte de este proyecto
#Directorio General Proyecto

blog/urls.py
from django.urls import path

from . import views


urlpatterns = [

    path('',views.blog,name="Blog"),
    #CREACION DE LA URLS DEL HTMOL CATEGORIAS:

    # categoria_id : Es especificacion el parametro,
    path('categoria/<int:categoria_id>/',views.categoria,name="categoria")
]

carro/urls.py
#urls de la aplicacion : 

#Importacion del path
from django.urls import path
#Importacion de Vistas 
from . import views


#para poder usar mas solidas 
app_name="carro"


urlpatterns = [
   
    #Primer urls para agregar productos
    #Pasamos el id del producto
    path('agregar/<int:producto_id>/', views.agregar_producto,name="agregar"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto,name="eliminar"),
    path('restar/<int:producto_id>/', views.restar_producto,name="restar"),
    path('limpiar/', views.limpiar_carro,name="limpiar"),
   
]      

tienda/urls.py
#urls de la aplicacion : 

#Importacion del path
from django.urls import path
#Importacion de Vistas 
from . import views





urlpatterns = [
   
    #Apunta a la raiz
    path('',views.tienda,name="Tienda"),
   
]      

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models
from django.db.models.deletion import CASCADE
#Pillow
# Create your models here.

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=100)
    # auto_now_add : para que se inserte en forma automatica
    created= models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "CategoriaProd"
        verbose_name_plural = "CategoriasProd"
    
    
    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(CategoriaProd,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda",null=True,blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)

    #agregar 
    created= models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural="Productos"

    def  __str__(self):
        return self.nombre
        

#Migraciones:
# python manage.py  makemigrations
# python manage.py migrate

carro/views.py
from django.shortcuts import render

from .carro import Carro

from tienda.models import Producto

from django.shortcuts import redirect


def agregar_producto(request, producto_id):

    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Tienda")

def eliminar_producto(request, producto_id):

    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Tienda")

def restar_producto(request, producto_id):

    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)

    carro.restar_productos(producto=producto)

    return redirect("Tienda")

def limpiar_carro(request, producto_id):

    carro=Carro(request)
    carro.limpiar_carro()
  

    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render
from .models import Producto
# Create your views here.
def tienda(request):

    producto = Producto.objects.all()


    return render(request,"tienda/tienda.html",{"productos":producto})

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color:white">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>

    <tbody>
              
        <!--Se han agregado articulos en el carro 
        q nos ponga , pero si no se han agregado q nos ponga 
        un mensaje-->
        <!--Es decir si hay elemento en el carro de la peticion de esta
        seccion tiene q recorrer tod los articulos y mostrarlo-->
       
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id%}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id%}" class="btn btn-sm btn-success">-</a>

                        {{value.precio}}$
                       
                       

                    </td>
                        

                </tr>


            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin Producto
                    </div>
                </td>
            </tr>
        {% endif %}
      
            
        
    </tbody>

    <tfoot>
        <td colspan="3">
            <p class="text-center">Total:{{importe_total_carro}}</p>
        </td>
    </tfoot>

</table>